<?php

namespace App\Enums;

enum ScholarType: string
{
    case REGULAR_COLLEGE ='REGULAR COLLEGE';
    case REGULAR_IP_COLLEGE ='REGULAR IP COLLEGE';
    case REGULAR_HIGH_SCHOOL ='REGULAR HIGH SCHOOL';
    case REGULAR_IP_HIGH_SCHOOL ='REGULAR IP HIGH SCHOOL';
    case CAMIA ='CAMIA';
    case CSP_2 ='CSP 2';
    case DSHP_ANIHAN ='DSHP ANIHAN';
    case DSHP_DUAL_TECH ='DSHP DUAL TECH';
    case DSHP_LUZVIMIN ='DSHP LUZVIMIN';
    case BALIK_ESKWELA_COLLEGE ='BALIK_ESKWELA COLLEGE';
    case BALIK_ESKWELA_HIGH_SCHOOL ='BALIK ESKWELA HIGH SCHOOL'; 
    case FORBES ='FORBES';
    case BROKENSHIRE ='BROKENSHIRE';
    case MBA_BOAT_PARTNERS ='MBA BOAT PARTNERS';
    case SPECIAL_SCHOLAR ='SPECIAL SCHOLAR';
    case MRI_EXCELLENCE_SCHOLARSHIP ='MRI EXCELLENCE SCHOLARSHIP';
    case CMDI_BAY_SENIOR_HIGH_SCHOOL ='CMDI BAY SENIOR HIGH SCHOOL';
    case CMDI_TAGUM_SENIOR_HIGH_SCHOOL ='CMDI_TAGUM SENIOR HIGH SCHOOL';
    case CMDI_BAY_COLLEGE ='CMDI BAY COLLEGE';
    case CMDI ='CMDI';
    
    public static function values(): array {
        return array_column(self::class->cases, 'value');
    }
}
